name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-musl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    - name: Install cross
      run: cargo install cross
      
    - name: Cache cross Docker image
      uses: actions/cache@v4
      with:
        path: ~/.cache/cross
        key: cross-${{ runner.os }}-x86_64-unknown-linux-musl
        
    - name: Build for x86_64-unknown-linux-musl
      run: cross build --release --target x86_64-unknown-linux-musl
          
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dfs2-x86_64-unknown-linux-musl
        path: target/x86_64-unknown-linux-musl/release/dfs2
        retention-days: 90
        
